version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./origin:/var/www
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    tty: true
    working_dir: /app
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    volumes:
      - ./api:/app
    command: sh -c "go run main.go"
